<?php

namespace AppBundle\Entity;

/**
 * GoldBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoldBookRepository extends \Doctrine\ORM\EntityRepository
{
}
